---
title: "S17305_ExploratoryAnalysis"
output: html_document
date: "2025-05-07"
---

```{r}
library(ggplot2)
library(ggpubr)
library(reshape2) 
library(RColorBrewer)
library(DESeq2)
library(edgeR)
```

# Data Import and Manipulation
```{r}
# import raw count matrix
S17305_alldata <- read.delim("~/Documents/Data/S17305_alldata_original_forAmani.txt", comment.char="#")
```

### cts file
```{r}
# create separate count matrix file
cts <- S17305_alldata
```

```{r}
# genes names as row names 
rownames(cts) <- cts$Ensembl.Gene.ID

# delete the gene names column 
cts <- subset(cts, select = - Ensembl.Gene.ID)
```

```{r}
# set the conditions / phenotypes as columns names 
samples_conditions <- 
  c("Ctrl8w_NaCl1", "Ctrl8w_NaCl2", "Ctrl8w_NaCl3", "Ctrl8w_NaCl4", "KO8w_NaCl1",
    "KO8w_NaCl2", "KO8w_NaCl3", "KO8w_NaCl4", "KO8w_NaCl5", "KO8w_NaCl6" ,
    "KO8w_AAV1",  "KO8w_AAV2", "KO8w_AAV3", "KO8w_AAV4", "KO8w_AAV5", "KO8w_AAV6",
    "Ctrl3w1", "Ctrl3w2", "Ctrl3w3", "Ctrl3w4", "KO3w1", "KO3w2", "KO3w3", "KO3w4",
    "KO3w5", "Ctrl3w5",  "KO3w6",  "Ctrl8w_NaCl5")

colnames(cts) <- samples_conditions
```

### cts_long file 
```{r}
cts_long <- melt(cts)
S17305_alldata_melt <- melt(S17305_alldata)

S17305_alldata_melt$variable <- substr(as.character(S17305_alldata_melt$variable), 1, nchar(as.character(S17305_alldata_melt$variable)) - 6)

cts_long$variable <- as.character(cts_long$variable)

cts_long$condition <- as.factor(substr(cts_long$variable, 1, nchar(cts_long$variable) - 1))
cts_long$sample <- S17305_alldata_melt$variable
```
### cpm_long file 
```{r}
# RPM 
s17305_DGEList <- DGEList(cts)
s17305_cpm <- cpm(s17305_DGEList)
View(s17305_cpm)
```

```{r}
cpm_long <- melt(s17305_cpm)
S17305_alldata_melt <- melt(S17305_alldata)

S17305_alldata_melt$variable <- substr(as.character(S17305_alldata_melt$variable), 1, nchar(as.character(S17305_alldata_melt$variable)) - 6)

cpm_long$variable <- as.character(cpm_long$Var2)

cpm_long$condition <- as.factor(substr(cpm_long$variable, 1, nchar(cpm_long$variable) - 1))
cpm_long$sample <- S17305_alldata_melt$variable
```

### coldata file
```{r}
# create the coldata file (sample information table)
sample_ID <- c("BMBL57", "BMBL58", "BMBL59", "BMBL61",  "BMBL62",  "BMBL63",
               'BMBL64',  'BMBL65', 'BMBL66', 'BMBL67', 'BMBL68', 'BMBL69',
               'BMBL70', 'BMBL71',  'BMBL72',  'BMBL73',  'BMBL91',  'BMBL92',
               'BMBL93',  'BMBL95',  'BMBL96',  'BMBL97',  'BMBL99', 'BMBL100',
               'BMBL101',  'BMBL113', 'BMBL114',  'BMBL115')
  

sample_name = c("8w_C18", "8w_C30", "8w_C53", "8w_C97", "8w_KONaCl26", "8w_KONaCl31", 
  "8w_KONaCl47", "8w_KONaCl71", "8w_KONaCl72", "8w_KONaCl76", "8w_KOAAV17", 
  "8w_KOAAV20", "8w_KOAAV49", "8w_KOAAV55", "8w_KOAAV92", "8w_KOAAV94", "3w_C3",
  "3w_C5", "3w_C15", "3w_C193", "3w_KO2", "3w_KO4", "3w_KO33", "3w_KO185",
  "3w_KO189", "3w_C54",  "3w_KO59", "8w_C93")

condition <- c(rep("Ctrl8w_NaCl", 4), rep("KO8w_NaCl", 6), 
               rep("KO8w_AAV", 6), rep("Ctrl3w", 4), rep("KO3w", 5), 
               "Ctrl3w", "KO3w", "Ctrl8w_NaCl")

coldata <- data.frame(sample_ID, sample_name, condition)
coldata$condition <- as.factor(coldata$condition)
```


# Exploratory analysis and visualization

## Descriptive statistics
### basic stats
```{r}
# total nb of samples
nb_samples <- ncol(cts)
cat("Number of samples:", nb_samples, "\n")

# nb of genes 
nb_genes <- nrow(cts)
cat("Number of genes:", nb_genes, "\n")

# nb of genes 
nb_cond <- length(table(coldata$condition))
cat("Number of conditions:", nb_cond, "\n")

# nb of samples per condition 
table(coldata$condition) 
```

### distributions
```{r}
# Histograms 
hist_raw <-
  ggplot(cts_long, aes(x = value)) +
  geom_histogram(bins = 50, fill = "#8ca4cb", color = "#8ca4cb") +
  scale_fill_brewer(palette = "Set2") + 
  labs(title = "A. Raw Read Count", x = "Read Count", y = "Count") +
  theme_minimal() + 
  theme(axis.title = element_text(size = 16), 
        axis.text = element_text(size = 14), 
        legend.text = element_text(size = 14), 
        legend.title = element_text(size = 14), 
        plot.title = element_text(size = 18))

hist_log <- 
ggplot(cts_long, aes(x = log2(value + 1))) + 
  geom_histogram(bins = 50, fill = "#8ca4cb", color = "#8ca4cb") + 
  labs(title = "B. Log scaled Read Count", x = "Read Count", y = "Count") +
  theme_minimal() +
  theme(axis.title = element_text(size = 16), 
        axis.text = element_text(size = 14), 
        legend.text = element_text(size = 14), 
        legend.title = element_text(size = 14), 
        plot.title = element_text(size = 18))

hist_norm <- 
ggplot(cpm_long, aes(x = log2(value + 1))) + 
  geom_histogram(bins = 50, fill = "#8ca4cb", color = "#8ca4cb") + 
  labs(title = "C. Log Scaled Normalized Read Count", x = "Read Count", y = "Count") +
  theme_minimal() + 
  theme(axis.title = element_text(size = 16), 
        axis.text = element_text(size = 14), 
        legend.text = element_text(size = 14), 
        legend.title = element_text(size = 14), 
        plot.title = element_text(size = 18))

readDistribution <- 
  ggarrange(hist_raw, hist_log, hist_norm,
          ncol = 3)
```

```{r eval=FALSE, include=FALSE}
ggsave("readDistribution.pdf", readDistribution,
       width = 16, height = 6, units = "in", dpi = 320, bg = "white")
```

### samples counts
```{r}
# nb of reads per sample 
readDistributionSamples <-
  ggplot(cts_long, aes(x = sample, y = value/10**6, fill = condition)) +
  geom_col() + 
  labs(x = "Samples", y = "Million Count") +
  theme_minimal() + 
  scale_fill_brewer(name = "Condition", labels = c("WT3w", "WT8w_NaCl", "KO3w", "KO8w_AAV", "KO8w_NaCl"), palette = "Set2") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
        axis.title = element_text(size = 16), 
        axis.text = element_text(size = 14), 
        legend.text = element_text(size = 14), 
        legend.title = element_text(size = 14), 
        plot.title = element_text(size = 18))
```

```{r eval=FALSE, include=FALSE}
ggsave("readDistributionSamples.pdf", readDistributionSamples,
       width = 16, height = 6, units = "in", dpi = 320, bg = "white")
```

### mean/var relationship
```{r}
# Computing mean and variance (+df)
mean_var <- data.frame(
  mean = rowMeans(cts), 
  var = apply(cts, 1, var))

# Mean and variance relationship
ggplot(mean_var, aes(x = log10(mean), y = log10(var))) + 
  geom_point(size = 0.3, alpha = 0.8) +
  geom_abline(intercept = 0, slope = 1) + 
  labs(y = expression(log[10](var)), x = expression(log[10](mean))) + 
  theme_minimal()
```

## DESeqDataSet (dds file)
```{r}
library(DESeq2)
dds <- DESeqDataSetFromMatrix(countData = cts,
                              colData = coldata,
                              design = ~ condition)
```

## PCA
```{r}
set.seed(123)
vsd <- varianceStabilizingTransformation(dds)

PCAplot <- 
  plotPCA(vsd, intgroup="condition") + 
  scale_color_brewer(name = "Condition", labels = c("WT3w", "WT8w_NaCl", "KO3w", "KO8w_AAV", "KO8w_NaCl"), palette = "Set2") +
  theme_minimal()+
  theme(axis.title = element_text(size = 16), 
        axis.text = element_text(size = 14), 
        legend.text = element_text(size = 14), 
        legend.title = element_text(size = 14), 
        plot.title = element_text(size = 18))
```
```{r eval=FALSE, include=FALSE}
ggsave("PCAplot.pdf", PCAplot,
       width = 16, height = 8, units = "in", dpi = 320, bg = "white")
```



