---
title: "S17305_Annotation_Enrichment"
output: html_document
date: "2025-05-21"
---

```{r}
library(tidyr)
library(dplyr)
library(enrichR)
library(ggplot2)
library(ggpubr)
```


# Annotated FRDA Gene List 
```{r}
# import DAVID Annotation data 
DAVID_Annotation <- read.delim2("/home/amani/Documents/FRDA_DAVID.txt") 
```

```{r}
## merge DAVID annotation with FRDA Gene List
annotated_FRDAList <- FRDAList %>%
  left_join(DAVID_Annotation, by = c("gene" = "ID"))
```


## export 
```{r eval=FALSE, include=FALSE}
write.csv(annotated_FRDAList, "/home/amani/Documents/S17305_DataAnalysis/annotated_FRDAList.csv", row.names =  F, quote = F)
```

# Enrichment Analysis 
```{r}
enrichment1 <- enrichr(identity1, "GO_Biological_Process_2023")

enrichmentPlot1 <- 
  plotEnrich(enrichment1[["GO_Biological_Process_2023"]])+
  ggtitle("A. KO8w-NaCl versus WT8w") + 
  theme(axis.title = element_text(size = 24), 
        axis.text = element_text(size = 20), 
        legend.text = element_text(size = 20), 
        legend.title = element_text(size = 24), 
        plot.title = element_text(size = 30))
  
```

```{r}
enrichment2 <- enrichr(identity2, "GO_Biological_Process_2023")

enrichmentPlot2 <- 
  plotEnrich(enrichment2[["GO_Biological_Process_2023"]]) + 
  ggtitle("B. KO8w-AAV versus KO8w-NaCl	") +
  theme(axis.title = element_text(size = 24), 
        axis.text = element_text(size = 20), 
        legend.text = element_text(size = 20), 
        legend.title = element_text(size = 24), 
        plot.title = element_text(size = 30))

```


```{r}
enrichment3 <- enrichr(identity3, "GO_Biological_Process_2023")

enrichmentPlot3 <- 
  plotEnrich(enrichment3[["GO_Biological_Process_2023"]]) + 
  ggtitle("C. KO8w-AAV versus WT8w-NaCl	") + 
  theme(axis.title = element_text(size = 24), 
        axis.text = element_text(size = 20), 
        legend.text = element_text(size = 20), 
        legend.title = element_text(size = 24), 
        plot.title = element_text(size = 30))
```

```{r}
enrichment4 <- enrichr(identity4, "GO_Biological_Process_2023")

enrichmentPlot4 <- 
  plotEnrich(enrichment4[["GO_Biological_Process_2023"]]) + 
  ggtitle("D. KO3w versus WT3w") + 
  theme(axis.title = element_text(size = 24), 
        axis.text = element_text(size = 20), 
        legend.text = element_text(size = 20), 
        legend.title = element_text(size = 24), 
        plot.title = element_text(size = 30))

```


```{r}
enrichmentPlot <-
  ggarrange(enrichmentPlot1, enrichmentPlot2, enrichmentPlot3, enrichmentPlot4, 
          ncol = 1, nrow = 4)
```


```{r eval=FALSE, include=FALSE}
ggsave("enrichmentPlot.pdf", enrichmentPlot,
       width = 22, height = 30, units = "in", dpi = 320, bg = "white")
```










